"""Auto-generated by tools/sync_progressions.py — do not edit by hand.

Source: data/player_maps/progressions.json
"""

from typing import Optional, TypedDict


class KeyItemEntry(TypedDict):
    item_name: str
    primary_map_id: int
    primary_map_hex: str
    unlocks_maps: list[int]
    unlocks_map_hexes: list[str]


class StoryCheckEntry(TypedDict):
    event_id: int
    event_hex: str
    ap_name: str
    map_id: int
    map_hex: str
    vanilla_gold: Optional[int]
    is_finish: bool
    key_name: Optional[str]
    blocks: list[int]


GRANDIA_KEY_ITEM_BASE = 0x4752_3000

START_MAP_IDS: list[int] = [8192, 9232]
START_MAP_HEXES: list[str] = ['2000', '2410']

KEY_ITEM_DATA: list[KeyItemEntry] = [
    {'item_name': 'Key to Sult Ruins', 'primary_map_id': 9216, 'primary_map_hex': '2400', 'unlocks_maps': [9216, 9220, 9222, 10248, 10252, 10260, 13320, 13324, 13325, 13328, 13332, 13340, 13344, 13348, 15445, 16396], 'unlocks_map_hexes': ['2400', '2404', '2406', '2808', '280C', '2814', '3408', '340C', '340D', '3410', '3414', '341C', '3420', '3424', '3C55', '400C']},
    {'item_name': "Key to Feena's House", 'primary_map_id': 16384, 'primary_map_hex': '4000', 'unlocks_maps': [16384, 23552, 15448, 23556], 'unlocks_map_hexes': ['4000', '5C00', '3C58', '5C04']},
    {'item_name': 'Key to Dom Ruins', 'primary_map_id': 17428, 'primary_map_hex': '4414', 'unlocks_maps': [17428, 17408, 17412, 17416, 17420, 16392, 19464, 19468, 19472, 20484, 18436, 22528, 22536], 'unlocks_map_hexes': ['4414', '4400', '4404', '4408', '440C', '4008', '4C08', '4C0C', '4C10', '5004', '4804', '5800', '5808']},
    {'item_name': 'Key to East Misty', 'primary_map_id': 22537, 'primary_map_hex': '5809', 'unlocks_maps': [22537], 'unlocks_map_hexes': ['5809']},
]

STORY_CHECK_DATA: list[StoryCheckEntry] = [
    {'event_id': 19, 'event_hex': '0x0013', 'ap_name': '(Parm) Intro Letter', 'map_id': 8192, 'map_hex': '2000', 'vanilla_gold': None, 'is_finish': False, 'key_name': 'Key to Sult Ruins', 'blocks': []},
    {'event_id': 32, 'event_hex': '0x0020', 'ap_name': '(Sult Ruins) Boss Defeated', 'map_id': 9222, 'map_hex': '2406', 'vanilla_gold': 30, 'is_finish': False, 'key_name': None, 'blocks': [9220, 9222]},
    {'event_id': 41, 'event_hex': '0x0029', 'ap_name': '(Leck Mines) Escape', 'map_id': 10260, 'map_hex': '2814', 'vanilla_gold': 60, 'is_finish': False, 'key_name': None, 'blocks': [9232, 10248, 10252, 10260]},
    {'event_id': 75, 'event_hex': '0x004B', 'ap_name': '(Ghost Ship) Completed', 'map_id': 13348, 'map_hex': '3424', 'vanilla_gold': 60, 'is_finish': False, 'key_name': None, 'blocks': [13320, 13324, 13325, 13328, 13332, 13340, 13344, 13348]},
    {'event_id': 83, 'event_hex': '0x0053', 'ap_name': '(New Parm) Membership Denied', 'map_id': 15445, 'map_hex': '3C55', 'vanilla_gold': None, 'is_finish': False, 'key_name': "Key to Feena's House", 'blocks': []},
    {'event_id': 93, 'event_hex': '0x005D', 'ap_name': '(New Parm) Boss Defeated', 'map_id': 15448, 'map_hex': '3C58', 'vanilla_gold': 120, 'is_finish': False, 'key_name': None, 'blocks': []},
    {'event_id': 96, 'event_hex': '0x0060', 'ap_name': '(Rangle Mountains) Night', 'map_id': 23556, 'map_hex': '5C04', 'vanilla_gold': None, 'is_finish': False, 'key_name': 'Key to Dom Ruins', 'blocks': []},
    {'event_id': 111, 'event_hex': '0x006F', 'ap_name': '(Military) Captured', 'map_id': 16392, 'map_hex': '4008', 'vanilla_gold': 120, 'is_finish': False, 'key_name': None, 'blocks': [15445, 15448, 16384, 16396, 17428, 17408, 17412, 17416, 17420, 16392, 23552, 23556]},
    {'event_id': 143, 'event_hex': '0x008F', 'ap_name': '(Military) Board Train', 'map_id': 19464, 'map_hex': '4C08', 'vanilla_gold': 120, 'is_finish': False, 'key_name': None, 'blocks': [19464, 19468, 19472]},
    {'event_id': 148, 'event_hex': '0x0094', 'ap_name': '(Military) Train Escape', 'map_id': 18436, 'map_hex': '4804', 'vanilla_gold': 120, 'is_finish': False, 'key_name': None, 'blocks': [20484]},
    {'event_id': 158, 'event_hex': '0x009E', 'ap_name': '(Luc Village) Defend Spirit Stone', 'map_id': 22536, 'map_hex': '5808', 'vanilla_gold': None, 'is_finish': False, 'key_name': 'Key to East Misty', 'blocks': []},
    {'event_id': 159, 'event_hex': '0x009F', 'ap_name': 'Temporary End', 'map_id': 22537, 'map_hex': '5809', 'vanilla_gold': None, 'is_finish': True, 'key_name': None, 'blocks': []},
]

FINISH_LOCATION_NAME: str = 'Temporary End'
FINISH_EVENT_ID: int = 159

# map_hex → key item name (every map gated by that key).
KEY_FOR_MAP: dict[str, str] = {}
for _key in KEY_ITEM_DATA:
    for _hx in _key["unlocks_map_hexes"]:
        KEY_FOR_MAP[_hx] = _key["item_name"]

# Primary hub hex → other unlocks (for optional parenting; all share same key rule).
KEY_HUB_CHILDREN: dict[str, list[str]] = {
    _key["primary_map_hex"]: [h for h in _key["unlocks_map_hexes"] if h != _key["primary_map_hex"]]
    for _key in KEY_ITEM_DATA
}

# Maps mentioned in progressions.json — only these participate in AP logic.
# Chest maps outside this set are ignored until added to progressions.
# Placement of Keys is left to the region tree (no accessible_maps list).
LOGIC_MAP_HEXES: set[str] = set(START_MAP_HEXES)
for _key in KEY_ITEM_DATA:
    LOGIC_MAP_HEXES.update(_key["unlocks_map_hexes"])
for _ev in STORY_CHECK_DATA:
    LOGIC_MAP_HEXES.add(_ev["map_hex"])
    LOGIC_MAP_HEXES.update(f"{b:04X}" for b in _ev["blocks"])

