#!/usr/bin/env python3
"""
Sync Archipelago APWorld tables from data/mdp_chest_catalog.json.

Writes:
  worlds/grandia/data/mdp_chest_catalog.json  (copy)
  worlds/grandia/Locations_data.py
  worlds/grandia/Items_data.py

Usage:
  python tools/sync_apworld_from_mdp_catalog.py
"""
from __future__ import annotations

import json
import shutil
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CATALOG = REPO / "data" / "mdp_chest_catalog.json"
ITEM_NAMES = REPO / "data" / "item_names.json"
WORLD = REPO / "worlds" / "grandia"
OUT_DATA = WORLD / "data"

# AP ids — must match client
LOCATION_BASE = 0x4752_2000  # + event_id
ITEM_BASE = 0x4752_0000  # + inventory item_id, or gold helper id
# Gold AP helper ids: 0x1000 + G amount (avoids clash with inventory 1–511 and reserved 0/1).
GOLD_AP_ID_BASE = 0x1000


def classify_item(kind: str, item_id: int) -> str:
    """Return Archipelago ItemClassification name: filler | useful | progression."""
    if kind == "gold":
        return "filler"
    # Permanent growth / skill books / rare utility — useful for now
    if item_id in range(377, 393):  # seeds + how-to books
        return "useful"
    if item_id in range(452, 460):  # fruits
        return "useful"
    if item_id in range(481, 489):  # poisons (permanent stats)
        return "useful"
    if item_id in range(489, 509):  # skill ups
        return "useful"
    # Equipment bands (weapons through boots/accessories)
    if 63 <= item_id <= 333:
        return "useful"
    # Consumables / food / bombs / scrolls
    return "filler"


def chest_location_name(area: str, event: int, loot_name: str, used: Counter) -> str:
    area = area.strip() or f"Map {event >> 8:02X}xx"
    base = f"{area} - {loot_name}"
    used[base] += 1
    if used[base] == 1:
        return base
    return f"{base} ({event:#06x})"


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    item_names = {int(k): v for k, v in json.loads(ITEM_NAMES.read_text(encoding="utf-8")).items()}

    # Deduplicate by event_id (first map wins).
    by_event: dict[int, dict] = {}
    for mid, mdata in sorted(catalog.items(), key=lambda kv: int(kv[0], 16)):
        area = mdata.get("area_name") or f"Map {mid}"
        for chest in mdata["chests"]:
            eid = int(chest["event"])
            if eid in by_event:
                continue
            by_event[eid] = {
                **chest,
                "map_hex": mdata["map_hex"],
                "area_name": area,
            }

    used_names: Counter = Counter()
    locations: list[dict] = []
    item_pool_counts: Counter = Counter()  # display name -> count
    item_meta: dict[str, dict] = {}

    for eid in sorted(by_event):
        c = by_event[eid]
        kind = c["kind"]
        iid = int(c["item_id"])
        if kind == "gold":
            gold_amount = int(c.get("gold_amount") or 0)
            loot_name = c.get("name") or (f"Gold ({gold_amount})" if gold_amount else "Gold")
            ap_item_name = loot_name
            # Unique AP id per G value (not game chest codes 1/2).
            item_id_for_ap = GOLD_AP_ID_BASE + gold_amount if gold_amount else iid
        else:
            loot_name = c.get("name") or item_names.get(iid, f"Item {iid}")
            ap_item_name = loot_name
            gold_amount = 0
            item_id_for_ap = iid

        classification = classify_item(kind, iid)
        loc_name = chest_location_name(c["area_name"], eid, loot_name, used_names)

        locations.append(
            {
                "event_id": eid,
                "event_hex": f"0x{eid:04X}",
                "ap_name": loc_name,
                "map_hex": c["map_hex"],
                "area_name": c["area_name"],
                "vanilla_kind": kind,
                "vanilla_item_id": iid,
                "vanilla_name": loot_name,
                "vanilla_gold": gold_amount,
            }
        )

        item_pool_counts[ap_item_name] += 1
        if ap_item_name not in item_meta:
            item_meta[ap_item_name] = {
                "name": ap_item_name,
                "item_id": item_id_for_ap,
                "kind": kind,
                "classification": classification,
                "gold_amount": gold_amount if kind == "gold" else 0,
            }

    OUT_DATA.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CATALOG, OUT_DATA / "mdp_chest_catalog.json")

    # Locations_data.py
    loc_lines = [
        '"""Auto-generated by tools/sync_apworld_from_mdp_catalog.py — do not edit by hand."""',
        "",
        "from typing import TypedDict",
        "",
        "",
        "class ChestLocationEntry(TypedDict):",
        "    event_id: int",
        "    event_hex: str",
        "    ap_name: str",
        "    map_hex: str",
        "    area_name: str",
        "    vanilla_kind: str",
        "    vanilla_item_id: int",
        "    vanilla_name: str",
        "    vanilla_gold: int",
        "",
        "",
        "CHEST_LOCATION_DATA: list[ChestLocationEntry] = [",
    ]
    for loc in locations:
        loc_lines.append(f"    {loc!r},".replace("'", '"') if False else f"    {json.dumps(loc)},")
    loc_lines.append("]")
    loc_lines.append("")
    (WORLD / "Locations_data.py").write_text("\n".join(loc_lines) + "\n", encoding="utf-8")

    # Items_data.py
    items_sorted = [item_meta[n] for n in sorted(item_meta, key=lambda n: (item_meta[n]["kind"], item_meta[n]["item_id"], n))]
    item_lines = [
        '"""Auto-generated by tools/sync_apworld_from_mdp_catalog.py — do not edit by hand."""',
        "",
        "from typing import TypedDict",
        "",
        "",
        "class ChestItemEntry(TypedDict):",
        "    name: str",
        "    item_id: int",
        "    kind: str",
        "    classification: str",
        "    gold_amount: int",
        "",
        "",
        "CHEST_ITEM_DATA: list[ChestItemEntry] = [",
    ]
    for it in items_sorted:
        item_lines.append(f"    {json.dumps(it)},")
    item_lines.append("]")
    item_lines.append("")
    item_lines.append("# vanilla chest pool counts (name -> quantity to put in itempool)")
    item_lines.append("CHEST_ITEM_POOL_COUNTS: dict[str, int] = {")
    for name, count in sorted(item_pool_counts.items(), key=lambda kv: (-kv[1], kv[0])):
        item_lines.append(f"    {json.dumps(name)}: {count},")
    item_lines.append("}")
    item_lines.append("")
    (WORLD / "Items_data.py").write_text("\n".join(item_lines) + "\n", encoding="utf-8")

    useful = sum(1 for it in items_sorted if it["classification"] == "useful")
    filler = sum(1 for it in items_sorted if it["classification"] == "filler")
    print(f"Locations (unique events): {len(locations)}")
    print(f"Distinct item types: {len(items_sorted)} (useful={useful}, filler={filler})")
    print(f"Item pool size: {sum(item_pool_counts.values())}")
    print(f"Wrote {WORLD / 'Locations_data.py'}")
    print(f"Wrote {WORLD / 'Items_data.py'}")
    print(f"Copied catalog -> {OUT_DATA / 'mdp_chest_catalog.json'}")


if __name__ == "__main__":
    main()
