#!/usr/bin/env python3
"""Sync data/player_maps/progressions.json → APWorld Keys_data + DLL progressions_generated.h.

Usage (repo root):
  python tools/sync_progressions.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PROGRESSIONS = REPO / "data" / "player_maps" / "progressions.json"
KEYS_DATA_OUT = REPO / "worlds" / "grandia" / "Keys_data.py"
DLL_HEADER_OUT = REPO / "client" / "Grandiarchipelago" / "progressions_generated.h"
APWORLD_COPY = REPO / "worlds" / "grandia" / "data" / "progressions.json"
LOCATIONS_DATA = REPO / "worlds" / "grandia" / "Locations_data.py"


def map_id_to_hex(map_id: int) -> str:
    return f"{map_id:04X}"


def load_chest_events_by_map() -> dict[str, list[int]]:
    """Parse CHEST_LOCATION_DATA without importing the package."""
    text = LOCATIONS_DATA.read_text(encoding="utf-8")
    by_map: dict[str, list[int]] = {}
    for m in re.finditer(
        r'\{"event_id":\s*(\d+),\s*"event_hex":\s*"[^"]+",\s*"ap_name":\s*"[^"]+",\s*"map_hex":\s*"([^"]+)"',
        text,
    ):
        eid, mhex = int(m.group(1)), m.group(2).upper()
        by_map.setdefault(mhex, []).append(eid)
    return by_map


def main() -> None:
    data = json.loads(PROGRESSIONS.read_text(encoding="utf-8"))
    start_maps: list[int] = list(data.get("start_maps", []))
    events: list[dict] = list(data.get("events", []))

    keys: list[dict] = []
    story: list[dict] = []
    lockouts: list[dict] = []
    finish_name: str | None = None
    finish_id: int | None = None

    for ev in events:
        eid = int(ev["id"])
        emap = int(ev["map"])
        name = str(ev["name"])
        entry = {
            "event_id": eid,
            "event_hex": f"0x{eid:04X}",
            "ap_name": name,
            "map_id": emap,
            "map_hex": map_id_to_hex(emap),
            "vanilla_gold": int(ev["gold"]) if "gold" in ev else None,
            "is_finish": bool(ev.get("finish")),
            "key_name": None,
            "blocks": [int(x) for x in ev.get("blocks", [])],
        }
        if "key" in ev:
            k = ev["key"]
            if "value" not in k:
                raise SystemExit(
                    f"Key on event {name!r} (id {eid}) is missing required integer field 'value'"
                )
            value = int(k["value"])
            if value < 1:
                raise SystemExit(
                    f"Key on event {name!r} (id {eid}) has invalid value {value} (must be >= 1)"
                )
            unlocks = [int(x) for x in k["unlocks_maps"]]
            primary = unlocks[0]
            keys.append(
                {
                    "item_name": str(k["name"]),
                    "value": value,
                    "primary_map_id": primary,
                    "primary_map_hex": map_id_to_hex(primary),
                    "unlocks_maps": unlocks,
                    "unlocks_map_hexes": [map_id_to_hex(x) for x in unlocks],
                }
            )
            entry["key_name"] = str(k["name"])
        if entry["is_finish"]:
            finish_name = name
            finish_id = eid
        if entry["blocks"]:
            lockouts.append(
                {
                    "event_id": eid,
                    "ap_name": name,
                    "blocks": entry["blocks"],
                    "blocks_hex": [map_id_to_hex(x) for x in entry["blocks"]],
                }
            )
        story.append(entry)

    chests_by_map = load_chest_events_by_map()
    for lo in lockouts:
        sweep: list[int] = []
        for mhex in lo["blocks_hex"]:
            sweep.extend(chests_by_map.get(mhex, []))
        lo["sweep_event_ids"] = sorted(set(sweep))

    logic_hexes: set[str] = {map_id_to_hex(x) for x in start_maps}
    for k in keys:
        logic_hexes.update(k["unlocks_map_hexes"])
    for s in story:
        logic_hexes.add(s["map_hex"])
        logic_hexes.update(map_id_to_hex(b) for b in s["blocks"])

    # APWorld check events: story locations + chests on progression-scoped maps only.
    known_events: set[int] = {int(s["event_id"]) for s in story}
    for mhex, eids in chests_by_map.items():
        if mhex.upper() in logic_hexes:
            known_events.update(eids)
    known_event_list = sorted(known_events)

    # --- Keys_data.py ---
    lines = [
        '"""Auto-generated by tools/sync_progressions.py — do not edit by hand.',
        "",
        "Source: data/player_maps/progressions.json",
        '"""',
        "",
        "from typing import Optional, TypedDict",
        "",
        "",
        "class KeyItemEntry(TypedDict):",
        "    item_name: str",
        "    value: int",
        "    primary_map_id: int",
        "    primary_map_hex: str",
        "    unlocks_maps: list[int]",
        "    unlocks_map_hexes: list[str]",
        "",
        "",
        "class StoryCheckEntry(TypedDict):",
        "    event_id: int",
        "    event_hex: str",
        "    ap_name: str",
        "    map_id: int",
        "    map_hex: str",
        "    vanilla_gold: Optional[int]",
        "    is_finish: bool",
        "    key_name: Optional[str]",
        "    blocks: list[int]",
        "",
        "",
        "GRANDIA_KEY_ITEM_BASE = 0x4752_3000",
        "",
        f"START_MAP_IDS: list[int] = {start_maps!r}",
        f"START_MAP_HEXES: list[str] = {[map_id_to_hex(x) for x in start_maps]!r}",
        "",
        "KEY_ITEM_DATA: list[KeyItemEntry] = [",
    ]
    for k in keys:
        lines.append(f"    {k!r},")
    lines += [
        "]",
        "",
        "STORY_CHECK_DATA: list[StoryCheckEntry] = [",
    ]
    for s in story:
        lines.append(f"    {s!r},")
    lines += [
        "]",
        "",
        f"FINISH_LOCATION_NAME: str = {finish_name!r}",
        f"FINISH_EVENT_ID: int = {finish_id!r}",
        "",
        "# map_hex → key item name (every map gated by that key).",
        "KEY_FOR_MAP: dict[str, str] = {}",
        "for _key in KEY_ITEM_DATA:",
        "    for _hx in _key[\"unlocks_map_hexes\"]:",
        "        KEY_FOR_MAP[_hx] = _key[\"item_name\"]",
        "",
        "# Key name → all key names with value <= this key's value (inclusive).",
        "# A key unlocks its maps only when the player has every name in this list.",
        "KEY_REQUIREMENTS: dict[str, list[str]] = {",
        "    _key[\"item_name\"]: [",
        "        e[\"item_name\"] for e in KEY_ITEM_DATA if e[\"value\"] <= _key[\"value\"]",
        "    ]",
        "    for _key in KEY_ITEM_DATA",
        "}",
        "",
        "# Primary hub hex → other unlocks (for optional parenting; all share same key rule).",
        "KEY_HUB_CHILDREN: dict[str, list[str]] = {",
        "    _key[\"primary_map_hex\"]: [h for h in _key[\"unlocks_map_hexes\"] if h != _key[\"primary_map_hex\"]]",
        "    for _key in KEY_ITEM_DATA",
        "}",
        "",
        "# Maps mentioned in progressions.json — only these participate in AP logic.",
        "# Chest maps outside this set are ignored until added to progressions.",
        "# Placement of Keys is left to the region tree (no accessible_maps list).",
        "LOGIC_MAP_HEXES: set[str] = set(START_MAP_HEXES)",
        "for _key in KEY_ITEM_DATA:",
        "    LOGIC_MAP_HEXES.update(_key[\"unlocks_map_hexes\"])",
        "for _ev in STORY_CHECK_DATA:",
        "    LOGIC_MAP_HEXES.add(_ev[\"map_hex\"])",
        "    LOGIC_MAP_HEXES.update(f\"{b:04X}\" for b in _ev[\"blocks\"])",
        "",
    ]
    KEYS_DATA_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # --- DLL header ---
    gated = sorted({m for k in keys for m in k["unlocks_maps"]})
    h: list[str] = [
        "// Auto-generated by tools/sync_progressions.py — do not edit by hand.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace grandia_ap {",
        "namespace progressions {",
        "",
        f"constexpr unsigned kMapKeyItemBase = 0x47523000u;",
        "",
        f"constexpr uint16_t kGatedMaps[] = {{",
        "  " + ", ".join(f"0x{m:04X}u" for m in gated) + ("," if gated else ""),
        "};",
        f"constexpr std::size_t kGatedMapCount = {len(gated)};",
        "",
    ]

    for i, k in enumerate(keys):
        maps = ", ".join(f"0x{m:04X}u" for m in k["unlocks_maps"])
        h.append(f"constexpr uint16_t kKey{i}Maps[] = {{ {maps} }};")
    h += [
        "",
        "// A key unlocks its maps only when every key with value <= this value is owned.",
        "struct KeyUnlockGroup {",
        "  uint16_t primary_map;",
        "  unsigned value;",
        "  const uint16_t* maps;",
        "  std::size_t count;",
        "};",
        "",
        "constexpr KeyUnlockGroup kKeyGroups[] = {",
    ]
    for i, k in enumerate(keys):
        h.append(
            f"  {{ 0x{k['primary_map_id']:04X}u, {int(k['value'])}u, kKey{i}Maps, "
            f"sizeof(kKey{i}Maps) / sizeof(kKey{i}Maps[0]) }},"
        )
    h += [
        "};",
        f"constexpr std::size_t kKeyGroupCount = {len(keys)};",
        "",
    ]

    for i, lo in enumerate(lockouts):
        ids = ", ".join(f"0x{e:04X}u" for e in lo["sweep_event_ids"]) or "0"
        h.append(
            f"constexpr uint16_t kLockout{i}Sweep[] = {{ {ids} }};"
            if lo["sweep_event_ids"]
            else f"constexpr uint16_t kLockout{i}Sweep[] = {{}};"
        )
    h += [
        "",
        "struct AreaLockout {",
        "  uint16_t event_id;",
        "  const uint16_t* sweep_events;",
        "  std::size_t sweep_count;",
        "};",
        "",
        "constexpr AreaLockout kAreaLockouts[] = {",
    ]
    for i, lo in enumerate(lockouts):
        n = len(lo["sweep_event_ids"])
        h.append(
            f"  {{ 0x{lo['event_id']:04X}u, kLockout{i}Sweep, {n} }},"
        )
    h += [
        "};",
        f"constexpr std::size_t kAreaLockoutCount = {len(lockouts)};",
        "",
        # Known AP location event ids (story + chests on LOGIC maps).
        "constexpr uint16_t kApCheckEvents[] = {",
        "  "
        + ", ".join(f"0x{e:04X}u" for e in known_event_list)
        + ("," if known_event_list else ""),
        "};",
        f"constexpr std::size_t kApCheckEventCount = {len(known_event_list)};",
        "",
        "inline bool IsApCheckEvent(uint16_t event_id) {",
        "  // kApCheckEvents is sorted ascending.",
        "  std::size_t lo = 0;",
        "  std::size_t hi = kApCheckEventCount;",
        "  while (lo < hi) {",
        "    const std::size_t mid = lo + (hi - lo) / 2;",
        "    const uint16_t v = kApCheckEvents[mid];",
        "    if (v == event_id) {",
        "      return true;",
        "    }",
        "    if (v < event_id) {",
        "      lo = mid + 1;",
        "    } else {",
        "      hi = mid;",
        "    }",
        "  }",
        "  return false;",
        "}",
        "",
        "}  // namespace progressions",
        "}  // namespace grandia_ap",
        "",
    ]
    DLL_HEADER_OUT.write_text("\n".join(h), encoding="utf-8")

    APWORLD_COPY.parent.mkdir(parents=True, exist_ok=True)
    APWORLD_COPY.write_text(PROGRESSIONS.read_text(encoding="utf-8"), encoding="utf-8")

    print(f"Wrote {KEYS_DATA_OUT.relative_to(REPO)}")
    print(f"Wrote {DLL_HEADER_OUT.relative_to(REPO)}")
    print(
        f"Keys={len(keys)} story={len(story)} gated_maps={len(gated)} "
        f"lockouts={len(lockouts)} ap_checks={len(known_event_list)}"
    )
    for lo in lockouts:
        print(f"  lockout 0x{lo['event_id']:04X}: sweep {len(lo['sweep_event_ids'])} chests")


if __name__ == "__main__":
    main()
