#pragma once
// Auto-generated by tools/sync_client_locations.py — do not edit by hand.

#include <cstddef>
#include <cstdint>

static constexpr uint16_t kKnownSlots[] = {
    38, 43, 72, 74, 75, 76, 77, 82, 84, 86, 88, 89,
    94, 95, 97, 98, 105, 106, 108, 114, 115, 116, 120, 121,
    124, 128, 131, 140, 146, 147, 149, 151, 154, 159, 161, 167,
    168, 169, 170, 180, 181, 183, 185, 190, 192, 194, 201, 204,
    211, 213, 214, 215, 222, 225, 230, 231, 238, 241, 243, 245,
    251, 254, 267, 268, 270, 271, 272, 273, 276, 278, 279, 283,
    288, 294, 299, 300, 301, 302, 303, 304, 305, 306, 308, 310,
    313, 315, 318, 321, 322, 324, 326, 327, 328, 329, 330, 332,
    333, 334, 340, 341, 347, 361, 362, 364, 376, 377, 378, 379,
    380, 381, 382, 383, 384, 395, 419, 421, 429, 434, 435, 436,
    439, 442, 443, 452, 453, 454, 455, 456, 457, 458, 459, 463,
    465, 468, 471, 472,
};

static constexpr size_t kKnownSlotCount = sizeof(kKnownSlots) / sizeof(kKnownSlots[0]);

inline bool IsKnownSlot(int slot_id) {
    for (size_t i = 0; i < kKnownSlotCount; ++i) {
        if (kKnownSlots[i] == static_cast<uint16_t>(slot_id)) {
            return true;
        }
    }
    return false;
}
